- packages/patches/gtk/nsview-embedding.patch
https://bugzilla.xamarin.com/show_bug.cgi?id=25537
> [gtk] Pass the correct pointer to find_nsview_at_pos().

- bockbuild/package.py
See each commit message, thanks
> More checks for None

- packages/pcl-reference-assemblies.py
Adds Xamarin.tvOS PCL Profiles
Also includes WatchOS PCL profiles from another pull request #31
> tvOS PCL Profiles

- packages/pcl-reference-assemblies.py
Adds Xamarin.WatchOS PCL profiles.
> WatchOS PCL Profiles

- packages/gtk+.py
- packages/patches/gtk/gtk-add-new-osx-versions.patch
- packages/patches/gtk/gtk-new-screen-updates-api.patch
Also adds version checking support up through Sierra
Sorry to keep asking you to review this. I had it on the wrong repo before :)
> [gtk] New screen updates API

- packages/gtk+.py
This may be causing performance regressions.
/cc @Therzok
> Remove new screen API patch

- README.md
Adjust README build phase to https://github.com/mono/mono/commit/7e96bcfa3864795f77a262cadf6aac880e9bec45
> Update README build phase

- packages/gtk+.py
- packages/patches/gtk/update_only_apple_keyboard_layout.patch
https://github.com/mono/bockbuild/pull/49 for 2017-08
> [gtk] Fix crashing when using Third-party IME

- packages/gtk+.py
- packages/patches/gtk/gtk-backing-scale-factor.patch
Sorry it took me awhile to make the PR for this, I was having trouble getting my non-retina Mac working to test it with.
> [GTK] Fix userSpaceScaleFactor deprecation warnings.

- packages/pango.py
- packages/patches/pango-get-shaper-for-ideographic-space.patch
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/573960
> [Pango] Get the font shaper for ideographic spaces

- packages/gtk+.py
- packages/patches/gtk/gtk-nsview-focus-tabbing.patch
- packages/patches/gtk/gtk-nsview-subview-focus-fixes.patch
Backport of https://github.com/mono/bockbuild/pull/82 for 2018-08
> [2018-08] [GTK] Fix focus handling to better handle subviews for GtkNSView

- packages/gtk-sharp.py
Fix from https://github.com/mono/gtk-sharp/pull/264
> [gtk-sharp] Bump to pick up a build fix

- bockbuild/package.py
Backport of #100.
/cc @akoeplinger @alexischr
> [2019-02] Fix https://github.com/mono/mono/issues/14957

- bockbuild/package.py
Backport of #100.
/cc @akoeplinger @alexischr
> [2019-06] Fix https://github.com/mono/mono/issues/14957

- packages/patches/gtk/0001-prevent-gdk-quartz-window-delegate-replacement.patch
> [2019-06] [Gtk] Fix previous patch build

- packages/patches/gtk/0001-prevent-gdk-quartz-window-delegate-replacement.patch
> [2019-02] [Gtk] Fix previous patch build

- packages/gtk-sharp.py
Backport of #114.
/cc @akoeplinger @Therzok
> [2019-08] Bump gtk#

- packages/gtk+.py
- packages/patches/gtk/gtkviewport-autoscroll.patch
> [GTK] Autoscroll GtkViewport when focus moves

- packages/gtk+.py
- packages/patches/gtk/gtkviewport-autoscroll.patch
Partially Fixes VSTS #752820
Backport of #126.
> [2019-10] [GTK] Autoscroll GtkViewport when focus moves

- packages/gtk-sharp.py
Backport of #129.
/cc @Therzok
> [2019-10] Bump gtk# for clipboard binding fix

- packages/gtk-sharp.py
Backport of #129.
/cc @Therzok
> [2019-08] Bump gtk# for clipboard binding fix

- packages/gtk-sharp.py
Backport of #136.
/cc @akoeplinger @Therzok
> [2019-12] Bump gtk# to get startup performance improvements in case of env var

- packages/gtk-sharp.py
Backport of #136.
/cc @akoeplinger @Therzok
> [2019-10] Bump gtk# to get startup performance improvements in case of env var

- packages/gtk+.py
- packages/patches/gtk/define-NSPasteboardTypeURL.patch
- packages/patches/gtk/gtk-pboard-types.patch
Waiting on https://github.com/mono/mono/pull/18080 to get a build to test with.
> [GTK] Switch to newer NSPasteboardType values.

- bockbuild/darwinprofile.py
Addresses https://github.com/mono/mono/issues/15521
> Re-enable validate_symlinks processing step

- packages/gtk+.py
- packages/patches/gtk/define-NSPasteboardTypeURL.patch
- packages/patches/gtk/gtk-pboard-types.patch
Waiting on https://github.com/mono/mono/pull/18080 to get a build to test with.
Backport of #139.
> [2019-10] [GTK] Switch to newer NSPasteboardType values.

- packages/gtk+.py
- packages/patches/gtk/define-NSPasteboardTypeURL.patch
- packages/patches/gtk/gtk-pboard-types.patch
Waiting on https://github.com/mono/mono/pull/18080 to get a build to test with.
Backport of #139.
> [2019-12] [GTK] Switch to newer NSPasteboardType values.

- packages/gtk+.py
- packages/patches/gtk/define-NSPasteboardTypeURL.patch
- packages/patches/gtk/gtk-pboard-types.patch
Waiting on https://github.com/mono/mono/pull/18080 to get a build to test with.
Backport of #139.
> [2019-08] [GTK] Switch to newer NSPasteboardType values.

- packages/gtk-sharp.py
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1055130
> Bump gtk# to fix regression

- packages/gtk-sharp.py
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1055130
Backport of #149.
/cc @Therzok
> [2019-10] Bump gtk# to fix regression

- packages/gtk-sharp.py
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1055130
Backport of #149.
/cc @Therzok
> [2019-12] Bump gtk# to fix regression

- packages/gtk-sharp.py
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1055130
Backport of #149.
/cc @akoeplinger @Therzok
> [2020-02] Bump gtk# to fix regression

- packages/pango.py
- packages/patches/pango-ctfaces-nil-check.patch
> [Pango] Add nil check before CFArrayGetCount()

- packages/pango.py
- packages/patches/pango-ctfaces-nil-check.patch
VSTS #1069059
Backport of #153.
> [2019-10] [Pango] Add nil check before CFArrayGetCount()

- packages/pango.py
- packages/patches/pango-ctfaces-nil-check.patch
VSTS #1069059
Backport of #153.
> [2020-02] [Pango] Add nil check before CFArrayGetCount()

- packages/pango.py
- packages/patches/pango-ctfaces-nil-check.patch
VSTS #1069059
Backport of #153.
> [2019-12] [Pango] Add nil check before CFArrayGetCount()

- packages/gtk+.py
- packages/patches/gtk/0078-Optimize-querying-symbolic-hotkeys.patch
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1092021/
> Optimize CopySymbolicHotkeys by adding file stamp heuristics

- packages/gtk+.py
- packages/patches/gtk/0078-Optimize-querying-symbolic-hotkeys.patch
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1092021/
Backport of https://github.com/mono/bockbuild/pull/165
> [2020-02] Optimize CopySymbolicHotkeys by adding file stamp heuristics
