mono/bockbuild

bockbuild/package.py
If self.sources is None, it is tried to be initialized with the
value of the default_sources static field of its class, but there
may be classes which don't provide it.
The commit[1] that introduced the extract_organization() function
didn't take this in account.
This happens when we have a dummy package such as the gconf-one:
https://github.com/mono/bockbuild/blob/mono-3.4.0-branch/packages/gconf-dummy.py
And was exposed when running the banshee's darwin profile, as
evidenced by the stacktrace in [2].
[1] mono@43d1f7c
[2] https://bugzilla.gnome.org/show_bug.cgi?id=750110#c0
=> [Package] Stop assuming that default_sources must exist

bockbuild/darwinprofile.py
Bockbuild was refactored in [1] and, as part of it, the
GCC flags -O0 and -ggdb3 were moved to be applied directly
the the self.gcc_flags (but only if self.cmd_options.debug).
But gcc_flags' extend method only allows 1 argument (array)
instead of N, like gcc_debug_flags.
So this commit fixes this regression, whose stacktrace can
be seen in this bug comment [2]
[1] https://github.com/mono/bockbuild/commit/00e0e8ec65f1f0dab3814621ae752ade2e57138c
[2] https://bugzilla.gnome.org/show_bug.cgi?id=750110#c1
=> [DarwinProfile] Fix TypeError in debug build

bockbuild/package.py
There are some packages which contain patches in the sources
which need to be retrieved before being applied. Recent
refactoring introduced this bogus call to self.rm() which
would remove the workspace of a package before trying to
download the second source (the workspace is at this point
very important because we have already used tar to extract
what we downloaded in the first source).
=> [package] fix regression about patch downloading

packages/pcl-reference-assemblies.py
Xamarin.tvOS framework has been renamed to Xamarin.TVOS
=> Add Xamarin.TVOS to supported framework files for PCLs

packages/pcl-reference-assemblies.py
Corresponding targets files added to Mono in https://github.com/mono/mono/pull/2199
=> Include PCL4.6 reference assemblies

bockbuild/package.py
This got regressed when moving to the public bockbuild.
It's basically a port of the revert of https://github.com/xamarin/bockbuild/commit/c1c4910f98ecbd865432be57cd9784bd1b8e432f
Original commit messages:
- Another copy_side_by_side fix (https://github.com/xamarin/bockbuild/commit/a2050e8a5272ab97bdfc1fec4b7e9dd9de8fbcb6)
- Fix for 'assymetrical' copy_side_by_side (https://github.com/xamarin/bockbuild/commit/a95bfdc8c9b6a902dc0bf5b17235d122e438399c)
- Only try renaming side-by-side second copy when the second copy exists (https://github.com/xamarin/bockbuild/commit/7d1d4ad083c65376d7d73c12e398b9a31ba9305b)
- Convert an assert error into a warning. The Mono package builds the executable 'mono-boehm' only under 32-bit arch. (https://github.com/xamarin/bockbuild/commit/7d1d4ad083c65376d7d73c …
=> Make Mono package default to 64bit

packages/gtk+.py, packages/patches/gtk/get-ascii-capable-keyboard-input-source.patch
Instead of TISCopyCurrentKeyboardLayoutInputSource(). This seems
to fix issues with some Cyrillic keyboard layouts not being able
to type shortcuts like Cmd-A, Cmd-S, etc.
https://bugzilla.xamarin.com/show_bug.cgi?id=5162
=> [gtk] Use TISCopyCurrentASCIICapableKeyboardInputSource()

packages/gtk+.py, packages/patches/gtk/update_only_apple_keyboard_layout.patch
ref #45
This issue is not only Google Japanese Input's problem.
Crashing also occurs under other IME (such as ATOK).
So when switching IME that third-party IME, we use old method `TISCopyCurrentKeyboardInputSource`.
```
$ cd mono
$ ./external/bockbuild/bb MacSDK --package --arch=darwin-universal
```
Install mono that you build.
```
$ git clone https://gist.github.com/yamachu/56f6f5c3086832db448e5174ea3e63cb
$ cd 56f6f5c3086832db448e5174ea3e63cb
$ make
$ make run # and switch IME (Google Japanese Input,  non-Latin keyboard, Russian keyboard...)
```
or
```
$ cd /Library/Frameworks/Mono.framework/Versions/5.4.0/lib
$ sudo mv sudo mv libgdk-quartz-2.0.0.dylib libgdk-quartz-2.0.0.dylib_
$ sudo mv libgdk-quartz-2.0.0.dylib.dSYM/ libgdk-quartz-2.0.0.dylib.dSYM_
$ sudo cp …
```
=> [gtk] Fix crashing when using Third-party IME

bockbuild/environment.py
Given,
env.set('XDG_CONFIG_HOME', '$HOME/.config')
.. then the value got exported as the literal string
`$HOME/.config`, with no shell expansion. And any subprocess would get
the unexpanded value for that env var.
This broke msbuild build on jenkins, because of ..
bockbuild/unixprofile.py:        self.env.set('XDG_CONFIG_HOME', '$HOME/.config')
.. and this being surfaced to nuget via mono's
`Environment.SpecialFolder.ApplicationData`. The nuget tasks treated the
`"$HOME/.config"` string as a relative path, causing build breakage.
For reference: https://github.com/mono/mono/pull/9112#issuecomment-397138139
=> Environment.set(key,val): Expand env vars in the value

packages/gtk+.py, packages/patches/gtk/gtk-imquartz-commit-on-focus-out.patch
Fixes VSTS #569768
In the GTK sources there is a comment that says `Commit any partially built strings or it'll mess up other GTK+ widgets in the window`, but the next line after that discards the preedit instead of committing it. When I changed it to actually commit then this appeared to fix the bug.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/569768
=> [gtk] When focusing out, commit the preedit instead of discarding

packages/gtk+.py, packages/patches/gtk/gtk-fix-find_nsview_at_pos-recursive.patch, packages/patches/gtk/gtk-imquartz-commit-on-focus-out.patch
This is to backport the following changes to 2018-04
https://github.com/mono/bockbuild/pull/66
https://github.com/mono/bockbuild/pull/68
=> [2018-04] Backport some GTK patches

packages/gtk+.py, packages/patches/gtk/gtk-fix-find_nsview_at_pos-recursive.patch, packages/patches/gtk/gtk-imquartz-commit-on-focus-out.patch
This is to backport the following changes to 2018-06
https://github.com/mono/bockbuild/pull/66
https://github.com/mono/bockbuild/pull/68
=> [2018-06] Backport GTK patches

bockbuild/darwinprofile.py
It should be noted that both point to the same binary: clang. The GCC alias tells clang to use libstdc++. Apple has ceased development of that library in favor of libc++. The functions added to libc++ that have not been backported to libstdc++ causes llvm to fail to build on CI today
=> [runtime] Fix reference to C compiler, 'xcrun gcc' fails when building llvm

packages/gtk+.py
https://github.com/mono/mono/issues/9592
I don't have a proper fix yet, so for now can we just disable this patch?
=> [GTK] Disable this patch for now to fix crasher.

packages/gtk+.py, packages/patches/gtk/popup-combo-box-with-arrows.patch
Changes the behaviour of GtkComboBox to match the behaviour of NSPopupButton and NSComboBox in Cocoa
Fixes VSTS #752354
=> [Gtk] Patch Gtk to popup the menu when using the arrow keys

bockbuild/util/util.py
Given:
`for root, subdirs, filelist in os.walk(dir):`
.. symlinks to directories are only returned in `subdirs`. So, they need
to handled explicitly.
This meant that when bockbuild tried to zip up the contents of mono and
msbuild to move to the staging directory, then such symlinks were not
picked up thus breaking the build.
=> iterate_dir: Include symlinks to dirs also

packages/gtk+.py, packages/patches/gtk/0001-prevent-gdk-quartz-window-delegate-replacement.patch
Replacing the GdkQuartzWindow delegate causes bad things to happen. This will
prevent it, and drop a message to console telling you not to.
=> [Gdk] Prevent GdkQuartzWindow having its delegate replaced.

packages/gtk+.py, packages/patches/gtk/nsview-embedding-skip-hidden-subviews.patch
Skip hidden views when trying to find an NSView at the given position.
=> Fix NSView embedding events - skip hidden subviews

bockbuild/darwinprofile.py
We used to not do that, and the default triple would do just fine, but recently a change has caused the pkg-config package 64-bit build to also result in 32-bit binaries. Explicitly setting the triple remedies this problem
=> [darwin] Use configure's --build option for 64-bit builds too

packages/gtk+.py, packages/patches/gtk/0001-gtk-combo-box-native-menu-hook.patch
Adds hooks to our Mac version of Gtk that the client can use to handle combo box menus.
Like this.
=> [Gtk] Add a hook for the client to override GtkComboBox menus

bockbuild/util/util.py
Given:
`for root, subdirs, filelist in os.walk(dir):`
.. symlinks to directories are only returned in `subdirs`. So, they need
to handled explicitly.
This meant that when bockbuild tried to zip up the contents of mono and
msbuild to move to the staging directory, then such symlinks were not
picked up thus breaking the build.
(cherry picked from commit 5d818c1af4d10c9325a40aa66dc0c994aa3e1781)
=> [2018-10] iterate_dir: Include symlinks to dirs also

bockbuild/util/util.py
Given:
`for root, subdirs, filelist in os.walk(dir):`
.. symlinks to directories are only returned in `subdirs`. So, they need
to handled explicitly.
This meant that when bockbuild tried to zip up the contents of mono and
msbuild to move to the staging directory, then such symlinks were not
picked up thus breaking the build.
(cherry picked from commit 5d818c1af4d10c9325a40aa66dc0c994aa3e1781)
=> [2019-02] iterate_dir: Include symlinks to dirs also

packages/patches/gtk/0001-prevent-gdk-quartz-window-delegate-replacement.patch
Cocoa unsets delegates when deallocating the window object, so we need to
allow that and not throw a critical message at that point
Fixes VSTS #935204
Fixes VSTS #935386
=> [Gtk] Allow Cocoa to unset the delegate when deallocating the window

packages/patches/gtk/0001-prevent-gdk-quartz-window-delegate-replacement.patch
Cocoa unsets delegates when deallocating the window object, so we need to
allow that and not throw a critical message at that point
Fixes VSTS #935204
Fixes VSTS #935386
Backport of #105.
=> [2019-02] [Gtk] Allow Cocoa to unset the delegate when deallocating the window

packages/patches/gtk/0001-prevent-gdk-quartz-window-delegate-replacement.patch
Cocoa unsets delegates when deallocating the window object, so we need to
allow that and not throw a critical message at that point
Fixes VSTS #935204
Fixes VSTS #935386
Backport of #105.
=> [2019-06] [Gtk] Allow Cocoa to unset the delegate when deallocating the window

packages/patches/pango-system-font-single.patch
familyName is not a copied string, so don't release it
Fixes VSTS #976682
=> [Pango] Don't release string from familyName

packages/gtk-sharp.py
Otherwise we'd revert the work done in https://github.com/mono/gtk-sharp/pull/273.
Discovered in https://github.com/mono/mono/issues/17028.
Backport of #122.
/cc @akoeplinger
=> [2019-08] Don't force mcs compiler in gtk-sharp.py

packages/gtk-sharp.py
Otherwise we'd revert the work done in https://github.com/mono/gtk-sharp/pull/273.
Discovered in https://github.com/mono/mono/issues/17028.
=> Don't force mcs compiler in gtk-sharp.py

packages/patches/pango-system-font-single.patch
familyName is not a copied string, so don't release it
Fixes VSTS #976682
Backport of #121.
=> [2019-08] [Pango] Don't release string from familyName

packages/patches/pango-system-font-single.patch
familyName is not a copied string, so don't release it
Fixes VSTS #976682
Backport of #121.
=> [2019-06] [Pango] Don't release string from familyName

bockbuild/unixprofile.py
So that python3 is found which is needed for the mono build.
I removed /usr/local/git/bin since it doesn't exist on our build bots anyway.
Backport of #144.
/cc @akoeplinger
=> [2020-02] Add /usr/local/bin to PATH

bockbuild/unixprofile.py
So that python3 is found which is needed for the mono build.
I removed /usr/local/git/bin since it doesn't exist on our build bots anyway.
=> Add /usr/local/bin to PATH

packages/gtk+.py, packages/patches/gtk/Fix-1080409-StackOverflow-exception-opening-Gtk-host.patch
Problem was that if `r.origin.x`/`r.origin.y` were 0, same value was looped until stackoverflow.
Whole logic of method assumes that it will loop over children hence recursive but in fact it kept passing same NSView over and over again...
=> Fix 1080409: StackOverflow exception opening Gtk hosted NSView

packages/gtk+.py, packages/patches/gtk/Fix-1080409-StackOverflow-exception-opening-Gtk-host.patch
Problem was that if `r.origin.x`/`r.origin.y` were 0, same value was looped until stackoverflow.
Whole logic of method assumes that it will loop over children hence recursive but in fact it kept passing same NSView over and over again...
Backport of #159.
/cc @akoeplinger @DavidKarlas
=> [2020-02] Fix 1080409: StackOverflow exception opening Gtk hosted NSView

packages/gtk+.py, packages/patches/gtk/Fix-1080409-StackOverflow-exception-opening-Gtk-host.patch
Problem was that if `r.origin.x`/`r.origin.y` were 0, same value was looped until stackoverflow.
Whole logic of method assumes that it will loop over children hence recursive but in fact it kept passing same NSView over and over again...
Backport of #159.
/cc @akoeplinger @DavidKarlas
=> [2019-12] Fix 1080409: StackOverflow exception opening Gtk hosted NSView

packages/cairo.py, packages/patches/cairo-bigsur.patch
BigSur's CoreGraphics seems to need a copy of the data to stick around longer than the surface,
so we provide it a copy of the data instead.
=> [Cairo] Fix Cairo on BigSur

packages/cairo.py, packages/patches/cairo-bigsur.patch
BigSur's CoreGraphics seems to need a copy of the data to stick around longer than the surface,
so we provide it a copy of the data instead.
Backport of #162.
/cc @sevoku @iainx
=> [2020-02] [Cairo] Fix Cairo on BigSur

packages/cairo.py, packages/patches/cairo-bigsur.patch
BigSur's CoreGraphics seems to need a copy of the data to stick around longer than the surface,
so we provide it a copy of the data instead.
Backport of #162.
/cc @sevoku @iainx
=> [2019-12] [Cairo] Fix Cairo on BigSur

packages/gtk-sharp.py
The original impl did not take into account exceptions marshalling across thread boundaries so it could end up with the error being accessed after being disposed
Fix this by querying the message in-place, and also clear the error after, to signal to glib that we've suceeded in recovering
Fixes devdiv.visualstudio.com/DevDiv/_workitems/edit/1247180
=> [GLib] Avoid keeping a reference to the error
